version: '3'
services:
  aom:
    image: mysql:8.0
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 13306:3306
    container_name: batch
    environment:
      MYSQL_ROOT_PASSWORD: batch
      MYSQL_DATABASE: batch
      MYSQL_USER: batch
      MYSQL_PASSWORD: batch
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
